"""Add provider_subscription_id

Revision ID: 1868fb794670
Revises: edb9948191b9
Create Date: 2026-09-11 23:53:55.532145
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1868fb794670'
down_revision = 'edb9948191b9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('status_updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.alter_column('players_online',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_subscription_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscriptions_provider_subscription_id'), ['provider_subscription_id'], unique=True)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_provider_subscription_id'))
        batch_op.drop_column('provider_subscription_id')

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.alter_column('players_online',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('status_updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    # ### end Alembic commands ###
