"""baseline

Revision ID: 231579b3feca
Revises: None
Create Date: 2026-06-30 13:05:51.649122
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231579b3feca'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('agent_port', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', 'draining', name='nodestate'), nullable=False),
    sa.Column('total_ram_mb', sa.Integer(), nullable=False),
    sa.Column('used_ram_mb', sa.Integer(), nullable=False),
    sa.Column('cpu_cores', sa.Float(), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ram_mb', sa.Integer(), nullable=False),
    sa.Column('cpu_limit', sa.Integer(), nullable=False),
    sa.Column('storage_mb', sa.Integer(), nullable=False),
    sa.Column('player_limit', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('auth_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('referrer_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by_id', sa.Uuid(), nullable=True),
    sa.Column('blockcoin_balance', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=128), nullable=True),
    sa.Column('google_sub', sa.String(length=128), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_referrer_code'), 'users', ['referrer_code'], unique=True)
    op.create_table('servers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('world_name', sa.String(length=128), nullable=False),
    sa.Column('join_code', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('created', 'provisioning', 'running', 'syncing', 'suspended', name='serverstate'), nullable=False),
    sa.Column('vm_provider', sa.Enum('oracle_free', 'hetzner', 'local_bedrock', name='vmprovider'), nullable=False),
    sa.Column('vm_id', sa.String(length=128), nullable=True),
    sa.Column('vm_ipv4', sa.String(length=64), nullable=True),
    sa.Column('vm_port', sa.Integer(), nullable=False),
    sa.Column('mc_config', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('creator_earnings_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_backup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('world_size_bytes', sa.Integer(), nullable=False),
    sa.Column('backup_count', sa.Integer(), nullable=False),
    sa.Column('backup_retention_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_join_code'), 'servers', ['join_code'], unique=True)
    op.create_index(op.f('ix_servers_node_id'), 'servers', ['node_id'], unique=False)
    op.create_index(op.f('ix_servers_owner_id'), 'servers', ['owner_id'], unique=False)
    op.create_table('backup_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cron_expression', sa.String(length=128), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('retention_count', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('skip_if_server_offline', sa.Boolean(), nullable=False),
    sa.Column('defer_if_job_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_schedules_owner_id'), 'backup_schedules', ['owner_id'], unique=False)
    op.create_index(op.f('ix_backup_schedules_server_id'), 'backup_schedules', ['server_id'], unique=False)
    op.create_table('bans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('xuid', sa.String(length=64), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unbanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('unbanned_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['unbanned_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'xuid', 'active', name='uq_bans_server_xuid_active')
    )
    op.create_index(op.f('ix_bans_server_id'), 'bans', ['server_id'], unique=False)
    op.create_table('blockcoin_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('referral', 'ad_view', 'daily_task', 'server_hosting', 'purchase', 'admin_adjustment', name='blockcoinreason'), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockcoin_ledger_user_id'), 'blockcoin_ledger', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'grace_period', 'suspended', 'cancelled', name='billingsubscriptionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_expires_at'), 'subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_server_id'), 'subscriptions', ['server_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('backups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('manual', 'scheduled', 'system', name='backupkind'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'held_saves', 'copying', 'compressing', 'verifying', 'completed', 'failed', 'cancelled', 'deleting', 'deleted', 'expired', name='backupstatus'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('world_name', sa.String(length=128), nullable=False),
    sa.Column('bedrock_version', sa.String(length=64), nullable=True),
    sa.Column('consistency_method', sa.Enum('save_hold', 'server_stop', 'filesystem_snapshot', name='backupconsistencymethod'), nullable=True),
    sa.Column('server_was_running', sa.Boolean(), nullable=False),
    sa.Column('storage_backend', sa.Enum('local', 's3', name='backupstoragebackend'), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('archive_format', sa.String(length=32), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uncompressed_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('included_paths', sa.JSON(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['backup_schedules.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_owner_id'), 'backups', ['owner_id'], unique=False)
    op.create_index(op.f('ix_backups_server_id'), 'backups', ['server_id'], unique=False)
    op.create_index(op.f('ix_backups_status'), 'backups', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_order_id', sa.String(length=128), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', 'refunded', name='billingtransactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_plan_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['target_plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index(op.f('ix_transactions_provider_order_id'), 'transactions', ['provider_order_id'], unique=True)
    op.create_index(op.f('ix_transactions_server_id'), 'transactions', ['server_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('backup_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'held_saves', 'copying', 'compressing', 'verifying', 'completed', 'failed', 'cancelled', 'deleting', 'deleted', 'expired', name='backupstatus'), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('progress_bytes', sa.BigInteger(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('force_offline', sa.Boolean(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_jobs_backup_id'), 'backup_jobs', ['backup_id'], unique=False)
    op.create_index(op.f('ix_backup_jobs_server_id'), 'backup_jobs', ['server_id'], unique=False)
    op.create_index(op.f('ix_backup_jobs_status'), 'backup_jobs', ['status'], unique=False)
    op.create_table('billing_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_audit_logs_server_id'), 'billing_audit_logs', ['server_id'], unique=False)
    op.create_index(op.f('ix_billing_audit_logs_user_id'), 'billing_audit_logs', ['user_id'], unique=False)
    op.create_table('restore_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backup_id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'validating_backup', 'stopping_server', 'extracting', 'validating_restore', 'swapping', 'starting_server', 'completed', 'failed', 'rolled_back', 'cancelled', name='restorestatus'), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('progress_bytes', sa.BigInteger(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('restart_after_restore', sa.Boolean(), nullable=False),
    sa.Column('server_was_running', sa.Boolean(), nullable=False),
    sa.Column('rollback_enabled', sa.Boolean(), nullable=False),
    sa.Column('rollback_path', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restore_jobs_backup_id'), 'restore_jobs', ['backup_id'], unique=False)
    op.create_index(op.f('ix_restore_jobs_server_id'), 'restore_jobs', ['server_id'], unique=False)
    op.create_index(op.f('ix_restore_jobs_status'), 'restore_jobs', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restore_jobs_status'), table_name='restore_jobs')
    op.drop_index(op.f('ix_restore_jobs_server_id'), table_name='restore_jobs')
    op.drop_index(op.f('ix_restore_jobs_backup_id'), table_name='restore_jobs')
    op.drop_table('restore_jobs')
    op.drop_index(op.f('ix_billing_audit_logs_user_id'), table_name='billing_audit_logs')
    op.drop_index(op.f('ix_billing_audit_logs_server_id'), table_name='billing_audit_logs')
    op.drop_table('billing_audit_logs')
    op.drop_index(op.f('ix_backup_jobs_status'), table_name='backup_jobs')
    op.drop_index(op.f('ix_backup_jobs_server_id'), table_name='backup_jobs')
    op.drop_index(op.f('ix_backup_jobs_backup_id'), table_name='backup_jobs')
    op.drop_table('backup_jobs')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_server_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_provider_order_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_backups_status'), table_name='backups')
    op.drop_index(op.f('ix_backups_server_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_owner_id'), table_name='backups')
    op.drop_table('backups')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_server_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expires_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_blockcoin_ledger_user_id'), table_name='blockcoin_ledger')
    op.drop_table('blockcoin_ledger')
    op.drop_index(op.f('ix_bans_server_id'), table_name='bans')
    op.drop_table('bans')
    op.drop_index(op.f('ix_backup_schedules_server_id'), table_name='backup_schedules')
    op.drop_index(op.f('ix_backup_schedules_owner_id'), table_name='backup_schedules')
    op.drop_table('backup_schedules')
    op.drop_index(op.f('ix_servers_owner_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_node_id'), table_name='servers')
    op.drop_index(op.f('ix_servers_join_code'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_users_referrer_code'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
