"""add_app_deployments

Revision ID: 32a9a713ba60
Revises: 04e234a355b7
Create Date: 2026-09-18 23:26:54.011660
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a9a713ba60'
down_revision = '04e234a355b7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('docker_image', sa.String(length=512), nullable=False),
    sa.Column('internal_port', sa.Integer(), nullable=False),
    sa.Column('host_port', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('created', 'building', 'running', 'stopped', 'error', name='deploymentstate'), nullable=False),
    sa.Column('env_vars', sa.JSON(), nullable=False),
    sa.Column('volume_path', sa.String(length=1024), nullable=False),
    sa.Column('volume_mount_path', sa.String(length=512), nullable=False),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('ram_limit_mb', sa.Integer(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_deployments_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_deployments_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_deployments_owner_id'))
        batch_op.drop_index(batch_op.f('ix_app_deployments_node_id'))

    op.drop_table('app_deployments')
    # ### end Alembic commands ###
