"""Initial migration

Revision ID: 44d3cd0fb8eb
Revises: None
Create Date: 2026-06-25 10:10:29.374433
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d3cd0fb8eb'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.VARCHAR(length=7), nullable=False))
    # ### end Alembic commands ###
