"""Add last_network_rx to AppDeployment

Revision ID: 6a01c3cf3030
Revises: 9f224c5d6e7f
Create Date: 2026-09-19 00:04:45.955101
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a01c3cf3030'
down_revision = '9f224c5d6e7f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_network_rx', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_deployments', schema=None) as batch_op:
        batch_op.drop_column('last_network_rx')

    # ### end Alembic commands ###
