"""add_server_collaborators

Revision ID: 6ee7c4a578e9
Revises: f2a6b8c9d0e1
Create Date: 2026-08-15 19:50:47.855444
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee7c4a578e9'
down_revision = 'f2a6b8c9d0e1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_collaborators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'user_id', name='uq_server_collaborators_server_user')
    )
    op.create_index(op.f('ix_server_collaborators_server_id'), 'server_collaborators', ['server_id'], unique=False)
    op.create_index(op.f('ix_server_collaborators_user_id'), 'server_collaborators', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_collaborators_user_id'), table_name='server_collaborators')
    op.drop_index(op.f('ix_server_collaborators_server_id'), table_name='server_collaborators')
    op.drop_table('server_collaborators')
    # ### end Alembic commands ###
