"""Add GitHub deployment columns

Revision ID: 8078c14c7f12
Revises: 21c9f518d116
Create Date: 2026-09-19 22:08:17.975584
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8078c14c7f12'
down_revision = '21c9f518d116'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_repo_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('github_branch', sa.String(length=128), server_default='main', nullable=False))
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('created', 'building', 'running', 'suspended', 'stopped', 'error', name='deploymentstate'),
               existing_nullable=False)



    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_deployments', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.Enum('created', 'building', 'running', 'suspended', 'stopped', 'error', name='deploymentstate'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('github_branch')
        batch_op.drop_column('github_repo_url')

    # ### end Alembic commands ###
