"""add_java_support

Revision ID: 879603959721
Revises: bf438b525946
Create Date: 2026-07-06 08:30:27.556626
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879603959721'
down_revision = 'bf438b525946'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backups', sa.Column('mc_version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backups', 'mc_version')
    # ### end Alembic commands ###
