"""baseline4

Revision ID: 89ce464b9e29
Revises: c75068a16348
Create Date: 2026-06-30 13:06:58.860595
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ce464b9e29'
down_revision = 'c75068a16348'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
