"""unified_billing

Revision ID: 8e113b433486
Revises: 32a9a713ba60
Create Date: 2026-09-18 23:40:51.477293
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e113b433486'
down_revision = '32a9a713ba60'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_webhook_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('billing_audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('resource_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('server_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_billing_audit_logs_resource_id'), ['resource_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('resource_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('server_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_subscriptions_resource_id'), ['resource_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('resource_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('server_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_transactions_resource_id'), ['resource_id'], unique=False)

    op.execute(
        "UPDATE subscriptions SET resource_type = 'minecraft_server', resource_id = server_id WHERE server_id IS NOT NULL AND resource_id IS NULL"
    )
    op.execute(
        "UPDATE transactions SET resource_type = 'minecraft_server', resource_id = server_id WHERE server_id IS NOT NULL AND resource_id IS NULL"
    )
    op.execute(
        "UPDATE billing_audit_logs SET resource_type = 'minecraft_server', resource_id = server_id WHERE server_id IS NOT NULL AND resource_id IS NULL"
    )

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_resource_id'))
        batch_op.alter_column('server_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.drop_column('resource_id')
        batch_op.drop_column('resource_type')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_resource_id'))
        batch_op.alter_column('server_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.drop_column('resource_id')
        batch_op.drop_column('resource_type')

    with op.batch_alter_table('billing_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_audit_logs_resource_id'))
        batch_op.alter_column('server_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.drop_column('resource_id')
        batch_op.drop_column('resource_type')

    op.drop_table('processed_webhook_events')
    # ### end Alembic commands ###
