"""Add proxy_port to Server

Revision ID: a3a5ffbbfb7f
Revises: 1f2a3b4c5d6e
Create Date: 2026-09-02 23:34:08.769971
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a5ffbbfb7f'
down_revision = '1f2a3b4c5d6e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('provider', sa.String(length=64), nullable=True))
    op.add_column('nodes', sa.Column('provider_instance_id', sa.String(length=128), nullable=True))
    op.alter_column('nodes', 'agent_port',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('servers', sa.Column('proxy_port', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'servers', ['proxy_port'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='unique')
    op.drop_column('servers', 'proxy_port')
    op.alter_column('nodes', 'agent_port',
               existing_type=sa.INTEGER(),
               server_default=sa.text('(9000)'),
               existing_nullable=False)
    op.drop_column('nodes', 'provider_instance_id')
    op.drop_column('nodes', 'provider')
    # ### end Alembic commands ###
