"""baseline7

Revision ID: a88e30983665
Revises: da49daca5283
Create Date: 2026-06-30 13:08:22.323739
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88e30983665'
down_revision = 'da49daca5283'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
