"""add hosting platform models

Revision ID: b10c569de78d
Revises: 8078c14c7f12
Create Date: 2026-09-21 15:30:07.566154
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10c569de78d'
down_revision = '8078c14c7f12'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_node_pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('instance_type', sa.String(length=64), nullable=False),
    sa.Column('image_id', sa.String(length=128), nullable=False),
    sa.Column('ssh_key_reference', sa.String(length=255), nullable=True),
    sa.Column('min_nodes', sa.Integer(), nullable=False),
    sa.Column('max_nodes', sa.Integer(), nullable=False),
    sa.Column('enabled_products', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)

    op.create_table('database_instances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('engine', sa.Enum('postgresql', 'mysql', 'mariadb', 'redis', name='databaseengine'), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('db_name', sa.String(length=64), nullable=False),
    sa.Column('db_username', sa.String(length=64), nullable=False),
    sa.Column('db_password', sa.String(length=255), nullable=False),
    sa.Column('internal_hostname', sa.String(length=128), nullable=False),
    sa.Column('internal_port', sa.Integer(), nullable=False),
    sa.Column('ram_limit_mb', sa.Integer(), nullable=False),
    sa.Column('cpu_limit', sa.Float(), nullable=False),
    sa.Column('storage_limit_mb', sa.Integer(), nullable=False),
    sa.Column('volume_path', sa.String(length=1024), nullable=False),
    sa.Column('state', sa.Enum('created', 'building', 'running', 'suspended', 'stopped', 'error', name='deploymentstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('database_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_database_instances_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_database_instances_project_id'), ['project_id'], unique=False)

    op.create_table('deployment_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('image_tag', sa.String(length=255), nullable=True),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('created', 'building', 'running', 'suspended', 'stopped', 'error', name='deploymentstate'), nullable=False),
    sa.Column('build_logs', sa.Text(), nullable=True),
    sa.Column('runtime_logs', sa.Text(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['app_deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_revisions_deployment_id'), ['deployment_id'], unique=False)

    with op.batch_alter_table('app_deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('deployment_kind', sa.Enum('docker_image', 'dockerfile', 'nextjs', 'fastapi', 'static_site', name='deploymentkind'), nullable=False, server_default='docker_image'))
        batch_op.add_column(sa.Column('source_type', sa.Enum('github', 'docker_image', 'upload', name='sourcetype'), nullable=False, server_default='docker_image'))
        batch_op.add_column(sa.Column('build_command', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('start_command', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('install_command', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('output_directory', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('runtime_version', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('health_check_path', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_app_deployments_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key('fk_app_deployments_projects', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('app_deployments', schema=None) as batch_op:
        batch_op.alter_column('deployment_kind', server_default=None)
        batch_op.alter_column('source_type', server_default=None)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_deployments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_app_deployments_project_id'))
        batch_op.drop_column('health_check_path')
        batch_op.drop_column('runtime_version')
        batch_op.drop_column('output_directory')
        batch_op.drop_column('install_command')
        batch_op.drop_column('start_command')
        batch_op.drop_column('build_command')
        batch_op.drop_column('source_type')
        batch_op.drop_column('deployment_kind')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('deployment_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_revisions_deployment_id'))

    op.drop_table('deployment_revisions')
    with op.batch_alter_table('database_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_database_instances_project_id'))
        batch_op.drop_index(batch_op.f('ix_database_instances_node_id'))

    op.drop_table('database_instances')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    op.drop_table('provider_node_pools')
    # ### end Alembic commands ###
