"""add_java_server_support

Revision ID: bf438b525946
Revises: c9d4e5f6a7b8
Create Date: 2026-07-05 12:02:10.810671
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf438b525946'
down_revision = 'c9d4e5f6a7b8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite does not support ALTER COLUMN DROP DEFAULT, so recreate the column definition instead.
    with op.batch_alter_table('nodes', recreate='always') as batch_op:
        batch_op.alter_column('approved', server_default=None)
    op.add_column('servers', sa.Column('flavor', sa.Enum('BEDROCK', 'JAVA_VANILLA', 'PAPER', 'PURPUR', 'FABRIC', 'FORGE', 'NEOFORGE', name='serverflavor'), nullable=True))
    op.add_column('servers', sa.Column('mc_version', sa.String(length=32), nullable=True))
    op.add_column('servers', sa.Column('java_version', sa.Integer(), nullable=True))
    op.execute("UPDATE servers SET flavor = 'BEDROCK' WHERE flavor IS NULL")
    with op.batch_alter_table('servers', recreate='always') as batch_op:
        batch_op.alter_column('flavor', nullable=False, server_default='BEDROCK')
    with op.batch_alter_table('servers', recreate='always') as batch_op:
        batch_op.create_unique_constraint('uq_servers_node_port', ['node_id', 'vm_port'])
    op.drop_index(op.f('uq_alive_subscription_per_server'), table_name='subscriptions', sqlite_where=sa.text("status IN ('active', 'grace_period')"))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_alive_subscription_per_server'), 'subscriptions', ['server_id'], unique=1, sqlite_where=sa.text("status IN ('active', 'grace_period')"))
    with op.batch_alter_table('servers', recreate='always') as batch_op:
        batch_op.drop_constraint('uq_servers_node_port', type_='unique')
    op.drop_column('servers', 'java_version')
    op.drop_column('servers', 'mc_version')
    op.drop_column('servers', 'flavor')
    with op.batch_alter_table('nodes', recreate='always') as batch_op:
        batch_op.alter_column('approved', server_default=sa.text('0'))
    # ### end Alembic commands ###
