"""baseline3

Revision ID: c75068a16348
Revises: e044c7be4771
Create Date: 2026-06-30 13:06:41.181064
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75068a16348'
down_revision = 'e044c7be4771'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
