"""baseline6

Revision ID: da49daca5283
Revises: ecd74734779b
Create Date: 2026-06-30 13:07:18.285364
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da49daca5283'
down_revision = 'ecd74734779b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
