"""baseline2

Revision ID: e044c7be4771
Revises: 231579b3feca
Create Date: 2026-06-30 13:06:28.550328
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e044c7be4771'
down_revision = '231579b3feca'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
