"""baseline5

Revision ID: ecd74734779b
Revises: 89ce464b9e29
Create Date: 2026-06-30 13:07:07.637779
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd74734779b'
down_revision = '89ce464b9e29'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
