"""Add status_updated_at to Node

Revision ID: edb9948191b9
Revises: a3a5ffbbfb7f
Create Date: 2026-09-06 21:46:04.694666
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb9948191b9'
down_revision = 'a3a5ffbbfb7f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.alter_column('agent_port',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('players_online', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_index(batch_op.f('uq_servers_proxy_port'))
        batch_op.create_unique_constraint('uq_servers_proxy_port', ['proxy_port'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('uq_servers_proxy_port'), ['proxy_port'], unique=1)
        batch_op.drop_column('players_online')

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('agent_port',
               existing_type=sa.INTEGER(),
               server_default=sa.text('(9000)'),
               existing_nullable=False)
        batch_op.drop_column('status_updated_at')

    # ### end Alembic commands ###
