name: blockhost_client
description: Minimal client to test BlockHost backend
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  google_sign_in: ^6.1.2
  font_awesome_flutter: ^11.0.0
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
